routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/SGECECST', function () {
    return view('welcome');
});


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

	Auth::routes();
	Route::group(['middleware' => 'auth'], function() {
    Route::get('gestion', function()
	{
   return view('gestion');
	});
 });	


Route::group(['middleware' => 'admin'], function() {
   	Route::resource('docentes','DocentesController');
   	Route::get('docentes/alta/{id}', [
      'uses'=> 'DocentesController@alta',
      'as'  => 'docentes.alta'
  ]);

	Route::resource('grados','GradosController');
	Route::resource('asignaciones','AsignacionesController');
	Route::resource('usuarios','UserController');
	
});
Route::group(['middleware' => 'auth'], function() {
	Route::resource('alumnos','AlumnosController');
	Route::get('alumnos/index2', [
      'uses'=> 'AlumnosController@index2',
      'as'  => 'alumnos.index2'
  ]);

	Route::resource('materias','MateriasController');
	Route::resource('examenes','ExamenesController');
	Route::get('examenes/modificar/{id}', [
      'uses'=> 'ExamenesController@modificar',
      'as'  => 'examenes.modificar'
  ]);
	Route::get('examenes/detalle/{idgrado}/{idalumno}/{trim}', [
      'uses'=> 'ExamenesController@detalle',
      'as'  => 'examenes.detalle'
  ]);
  Route::get('examenes/promedioFinal/{idgrado}/{idalumno}', [
      'uses'=> 'ExamenesController@promedioFinal',
      'as'  => 'examenes.promedioFinal'
  ]);
	Route::get('examenes/materias/{id}', [
      'uses'=> 'ExamenesController@materias',
      'as'  => 'examenes.materias'
  ]);
  Route::get('examenes/listado/{id}', [
      'uses'=> 'ExamenesController@listado',
      'as'  => 'examenes.listado'
  ]);
	Route::resource('asignacionAlumnosGrados','AsignacionAlumnosGradosController');
	Route::resource('asignacionMateriasGrados','AsignacionMateriasGradosController');
	Route::resource('eventos','EventosController');
	Route::resource('asistencias','AsistenciasController');
	Route::get('asistencias/modificar/{id}', [
      'uses'=> 'AsistenciasController@modificar',
      'as'  => 'asistencias.modificar'
  ]);
	Route::get('asistencias/detalle/{id}', [
      'uses'=> 'AsistenciasController@detalle',
      'as'  => 'asistencias.detalle'
  ]);

  Route::resource('reportes','ReportesController');
	Route::resource('promedios','PromediosController');

});

app/Promedios.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promedios extends Model
{
    protected $fillable = ['id_asignaciones','id_asignacionAlumnosGrados','id_asignacionMateriasGrados','id_examenes','trimestre1','trimestre2','trimestre3','prom_final','anio'];
    protected $dates = ['created_at','updated_at'];

    public function scopeNombre($query, $id_examenes)
	{
		return $query->where('id_examenes', 'LIKE', "%$id_examenes%");
	}

	public function Asignaciones(){
    return $this->belongsTo('App\Asignaciones', 'id_asignaciones');
}

public function AsignacionMateriasGrados(){
    return $this->belongsTo('App\AsignacionMateriasGrados', 'id_asignacionMateriasGrados');
}

public function AsignacionAlumnosGrados(){
    return $this->belongsTo('App\AsignacionAlumnosGrados', 'id_asignacionAlumnosGrados');
}

public function Examenes(){
    return $this->belongsTo('App\Examenes', 'id_examenes');
}

}

app/Http/Controllers/PromediosController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\AsignacionMateriasGrados;
use App\Asignaciones;
use App\Examenes;
use App\Promedios;
use Promedios1\http\Request\PromediosRequest;
use DB;



class PromediosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $nombre =$request->get('nombre');
        $promedios = Promedios::orderBy('id','DESC')->nombre($nombre)->paginate(10);
        return view('promedios.index',compact('promedios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()    {
       $examenes = Examenes::all();
       $asignacionAlumnosGrados = AsignacionAlumnosGrados::all();
      return view('promedios.create',compact('examenes','asignacionAlumnosGrados'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)    {
        $this->validate($request,[

          'id_asignaciones',
          'id_asignacionAlumnosGrados',
          'id_asignacionMateriasGrados',
          'id_examenes',
          'trimestre1',
          'trimestre2',
          'trimestre3',
          'prom_final',
            'anio'
        ]);
        
        Promedios::create($request->all());
        return redirect()->route('promedios.index')->with('success','Promedio guardado con éxito');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $identificador = Grados::find($id);
        $alumnos = Alumnos::orderBy('id','ASC')->pluck('nombre','id');
        //$grados = Grados::orderBy('id','ASC')->pluck('nombre','id');
        $asistencias = Asistencias::all();
        //$asignacion = AsignacionAlumnosGrados::orderBy('id','ASC')->pluck('id_alumno','id_grado');
        return view('asistencias.show')->with('identificador',$identificador)->with('asistencias',$asistencias)->with('alumnos',$alumnos);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)    {
        $identificador = Grados::find($id);
        $alumnos = Alumnos::orderBy('id','ASC')->pluck('nombre','id');
        //$grados = Grados::orderBy('id','ASC')->pluck('nombre','id');
        $asignacion = AsignacionAlumnosGrados::all();
        //$asignacion = AsignacionAlumnosGrados::orderBy('id','ASC')->pluck('id_alumno','id_grado');
        return view('asistencias.edit')->with('identificador',$identificador)->with('asignacion',$asignacion)->with('alumnos',$alumnos);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**
        foreach ($request->get('estado') as $key => $value) {
            $asistencias = Asistencias::find($request->get('id')[$key]);
            //$asistencias = new Asistencias;
            $asistencias->id_asig_alum_gr = $request->get('id_asig_alum_gr')[$key];
            $asistencias->estado = $value;
            $asistencias->fecha = $request->get('fecha');            
            $asistencias->update();
        }
        //Asistencias::find($id)->update($request->all());
        return redirect()->route('asistencias.index');*/

        $this->validate($request,[
          'estado',
        ]);
        Asistencias::find($id)->update($request->all());
        return redirect()->route('asistencias.index')->with('success','Asistencia actualizada con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
 
}

resources/views/promedios/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    	<h3 style="text-align:center"> DATOS DEL DOCENTE</h3>
    	<br>
      {{ Form::open(['route'=>'promedios.store', 'method'=>'POST']) }}
        @include('promedios.form_master')
      {{ form::close() }}
    </div>
  </div>
@endsection

resources/views/promedios/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    	<h3 style="text-align:center"> ACTUALIZACION DE DATOS DE DOCENTE</h3>
    	<br>
      {{ Form::model($docente,['route'=>['docentes.update',$docente->id],'method'=>'PATCH']) }}
      @include('docentes.form_master')
      {{ Form::close() }}
    </div>
  </div>
@endsection

resources/views/promedios/form_master.blade.php
   <div class="row">
    <div class="col-sm-3">
      {!! form::label('Nombre') !!}
    </div>
     <div class="col-sm-8">
      <div class="form-group {{ $errors->has('id_usuario') ? 'has-error' : "" }}">
      <i><select name="id_usuario" class="form-control">
               <option disabled selected>Seleccione el docente</option>
                @foreach($users as $user)
                  @if ($user->usuario=='Docente')
                      <option value="{{$user->id}}">{{$user->name}}</option>
                  @endif
                 @endforeach
            </select></i>
            <div class="help-block"> 
                <strong>{{ $errors->first('id_usuario', 'Seleccione uno') }}</strong>
          </div>
 </div>
</div>
 </div>
    <div class="row">
    <div class="col-sm-3">
      {!! form::label('no_dui','No. de DUI') !!}
    </div>
    <div class="col-sm-5">
      <div class="form-group {{ $errors->has('no_dui') ? 'has-error' : "" }}">
       <i>{{ Form::text('no_dui',NULL, ['class'=>'form-control','id'=>'no_dui','placeholder'=>'xxxxxxxx-x','maxlength' => 10]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('no_dui', 'Ingrese DUI correctamente') }}</strong>
      </div>
    </div>
  </div>
      </div>
  <div class="row">
    <div class="col-sm-3">
      {!! form::label('no_escalafon','No. de Escalafón') !!}
    </div>
    <div class="col-sm-5">
      <div class="form-group {{ $errors->has('no_escalafon') ? 'has-error' : "" }}">
       <i>{{ Form::text('no_escalafon',NULL, ['class'=>'form-control', 'id'=>'no_escalafon', 'placeholder'=>'xxxxxxx','maxlength' => 7]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('no_escalafon', 'Ingrese Escalafón correctamente') }}</strong>
      </div>
    </div>
    </div>
   </div>
   <div class="row">
    <div class="col-sm-3">
      {!! form::label('telefono','Teléfono') !!}
    </div>
    <div class="col-sm-5">
      <div class="form-group {{ $errors->has('telefono') ? 'has-error' : "" }}">
       <i>{{ Form::text('telefono',NULL, ['class'=>'form-control', 'id'=>'telefono', 'placeholder'=>'xxxxxxxx','maxlength' => 8]) }} </i> 
        <div class="help-block"> 
          <strong>{{ $errors->first('telefono', 'Ingrese Teléfono correctamente') }}</strong>
      </div>
    </div>
  </div>
      </div>
   <div class="row">
    <div class="col-sm-3">
      {!! form::label('direccion','Direccion') !!}
    </div>
    <div class="col-sm-8">
    <div class="form-group {{ $errors->has('direccion') ? 'has-error' : "" }}">
      <i>{{Form :: text ('direccion', NULL, ['class'=>'form-control', 'id'=>'direccion', 'placeholder'=>'Direccion'])}}</i>
        <div class="help-block"> 
          <strong>{{ $errors->first('direccion', 'Ingrese Direccion correctamente') }}</strong>
    </div>
    </div>
    </div>

    <div class="row">
    <div class="col-sm-3">
      {!! form::label('estado','Estado') !!}
    </div>
    <div class="col-sm-5">
        <i>{{ Form::select('estado', ['1'=>'Activo', '0'=>'Inactivo'], null, ['class'=>'form-control']) }}</i>
      </div>
    </div>
 
    <br>
       <div class="form-group text-center" >
      {{ Form::button(isset($model)? 'Update' : 'Guardar' , ['class'=>'btn btn-success btn-lg','type'=>'submit']) }}
      <a class="btn btn-danger btn-lg" href="{{ route('docentes.index') }}">Cancelar</a>
    </div>

    <!--Script para Colocar guion automatico en numero de DUI-->
<script type="text/javascript">
  $(document).ready(Principal);
    function Principal(){
        var flag1 = true;
        $(document).on('keyup','[id=no_dui]',function(e){
            if($(this).val().length == 8 && flag1) {
                $(this).val($(this).val()+"-");
                flag1 = false;
            }
        });
    }
</script> 

resources/views/promedios/index.blade.php
@extends ('layouts.app')
@section('content')
  <div class="row">
    <div class ="col-sm-12">
      <div class="full.right">
      <h2>PROMEDIOS FINALES</h2>
      <br>
      </div>
    </div>
  </div>
  @if ($message = Session::get('success'))
      <div class="alert alert-success">
          <p>{{ $message }}</p>
      </div>
  @endif
   @if ($message = Session::get('danger'))
      <div class="alert alert-danger">
          <p>{{ $message }}</p>
      </div>
  @endif
      <div>
        <a href="{{route('promedios.create')}}" class="btn btn-success btn-lg">
            <i class="glyphicon glyphicon-plus"> NUEVO</i>
        </a>
        {!! Form::open(['route'=>'promedios.index', 'method'=>'GET', 'class'=>'navbar-form pull-right', 'role'=>'search'])!!}
        <div class="input-group"> 
            {!! Form::text('nombre', null, ['class'=>'form-control', 'placeholder'=>'Buscar'])!!}
        </div>
         <button type="submit" class="glyphicon glyphicon-search btn-sm" data-toggle="tooltip" data-placement="top" title="Buscar"></button>
        {!! Form::close()!!}
      </div>
      <br>
  <table class="table table-striped" style="text-align:center" >
    <tr>
      <th with="80px">No</th>
      <th style="text-align:center">Nombre</th>
      <th style="text-align:center">Promedio</th>
      <th style="text-align:center">Accion</th>
    </tr>
    <?php $no=1; ?>
    @foreach ($promedios as $key => $value)
    <tr>
        <td>{{$no++}}</td>
        <td>{{ $value->AsignacionAlumnosGrados->Alumnos->nombre }}</td>
        <td>{{ $value->prom_final }}</td>
        <td>
          <a class="btn btn-info btn-lg" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('promedios.show',$value->id)}}">
              <i class="glyphicon glyphicon-list-alt"></i></a>
          <a class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('promedios.edit',$value->id)}}">
              <i class="glyphicon glyphicon-pencil"></i></a>
            {!! Form::open(['method' => 'DELETE','route' => ['promedios.destroy', $value->id],'style'=>'display:inline']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-lg" onclick="return confirm('¿Esta seguro de eliminar este Registro?')"><i class="glyphicon glyphicon-trash" ></i></button>
            {!! Form::close() !!}
        </td>
      </tr>
    @endforeach
  </table>
  {!!$promedios->render()!!}
 <div class="text-center">
    <a class="btn btn-primary" href="{{ url('/gestion') }}">Regresar</a>
  </div>
@endsection


  

resources/views/promedios/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row"  >
    <div class="col-lg-12 margin-tb">
        <div class="pull-left ">
            <h3 > DATOS DEL DOCENTE</h3>
            <br>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Nombres : </strong>
            {{ $docente->User->name}}
        </div>
    </div>
  
     <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Número de DUI: </strong>
            {{ $docente->no_dui}}
        </div>
    </div>
     <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Número de Escalafon : </strong>
            {{ $docente->no_escalafon}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Número de Teléfono : </strong>
            {{ $docente->telefono}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Dirección: </strong>
            {{ $docente->direccion}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Correo Electrónico: </strong>
            {{ $docente->User->email}}
        </div>
    </div>
    </div>
            <br/>
            <a class="btn btn-primary" href="{{ route('docentes.index') }}"> <i class="glyphicon glyphicon-arrow-left"> Regresar</i></a>
    </div>

@endsection